"""Typed Python client + CLI for the agent-memory MCP server."""

from .client import (
    AgentMemory,
    CaptureOutcome,
    MergedSearchResponse,
    SearchResponse,
    ThoughtsSearchResponse,
    ToolReply,
)
from .connect import (
    DEFAULT_TIMEOUT,
    DEFAULT_URL,
    ConnectOptions,
    CustomTransportOptions,
    HttpConnectOptions,
    StdioConnectOptions,
)
from .errors import (
    AgentMemoryError,
    AuthError,
    ParseError,
    ToolError,
    ToolErrorKind,
    TransportError,
    classify_tool_error_text,
)
from .parse import parse_document, parse_merged_results, parse_tree_list, parse_tree_node, parse_tree_search
from .sync import SyncAgentMemory
from .types import (
    CORPORA,
    DOCUMENT_BODY_MAX_CHARS,
    DOCUMENT_TAINTS,
    DOCUMENTS_UNAVAILABLE_NOTE,
    RELEVANCE_MODES,
    SYNC_SOURCE_KINDS,
    TREE_NODE_STATES,
    TREE_OPS,
    Corpus,
    DocumentHit,
    DocumentTaint,
    MergedHit,
    ParsedDocument,
    ParsedMergedResults,
    ParsedTreeList,
    ParsedTreeNode,
    ParsedTreeSearch,
    RankedThought,
    RelevanceMode,
    SyncSourceKind,
    ThoughtHit,
    TreeListEntry,
    TreeNodeState,
    TreeOp,
    TreeSearchHit,
    TreeWindow,
)

__version__ = "0.1.0"

__all__ = [
    "CORPORA",
    "DEFAULT_TIMEOUT",
    "DEFAULT_URL",
    "DOCUMENTS_UNAVAILABLE_NOTE",
    "DOCUMENT_BODY_MAX_CHARS",
    "DOCUMENT_TAINTS",
    "RELEVANCE_MODES",
    "SYNC_SOURCE_KINDS",
    "TREE_NODE_STATES",
    "TREE_OPS",
    "AgentMemory",
    "AgentMemoryError",
    "AuthError",
    "CaptureOutcome",
    "ConnectOptions",
    "Corpus",
    "CustomTransportOptions",
    "DocumentHit",
    "DocumentTaint",
    "HttpConnectOptions",
    "MergedHit",
    "MergedSearchResponse",
    "ParseError",
    "ParsedDocument",
    "ParsedMergedResults",
    "ParsedTreeList",
    "ParsedTreeNode",
    "ParsedTreeSearch",
    "RankedThought",
    "RelevanceMode",
    "SearchResponse",
    "StdioConnectOptions",
    "SyncAgentMemory",
    "SyncSourceKind",
    "ThoughtHit",
    "ThoughtsSearchResponse",
    "ToolError",
    "ToolErrorKind",
    "ToolReply",
    "TransportError",
    "TreeListEntry",
    "TreeNodeState",
    "TreeOp",
    "TreeSearchHit",
    "TreeWindow",
    "__version__",
    "classify_tool_error_text",
    "parse_document",
    "parse_merged_results",
    "parse_tree_list",
    "parse_tree_node",
    "parse_tree_search",
]
